---
- name: Install Prerequisites
  ansible.builtin.apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
  loop: [ 'aptitude' ]

- name: Install LEMP Packages
  ansible.builtin.apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'nginx', 'php-fpm' ]
