---
- name: Deploy my PHP application.
  hosts: jump_box
  become: true
  vars_files:
    - settings.yml
  tasks:
    - include_tasks: tasks/install_packages.yml
    - include_tasks: tasks/configure_nginx.yml
    - include_tasks: tasks/deploy_php_app.yml
    - include_tasks: tasks/reload.yml
